### ISSUE TITLE
Many thanks for this

### ISSUE THREAD

**Issue by simonjoom** [Jekiwijaya/react-navigation-browser-history-helpers#5]
I'm creating a web-app with react native api and i would like to add browser history 
I just found your repo! 

Many thanks.
Simon

**Comment by Jekiwijaya** [comment]
@simonjoom glad you like it. Just share with us if got a bug when using this library.

This library is also being used in my company to be able porting react-native codes to mobile web.
I haven't been able to provide documentation & tests. But it would going to be until it become mature.

**Comment by simonjoom** [comment]
I just added it in my project, didn't see any problem work very good, 
I used the last react-navigation it's compatible

**Comment by kopax** [comment]
Hello. I want to use browser history and I am discovering react-navigation through expo.
I don't see anything about it in the react-navigation documentation. Should I use this? I am not sure how.
